spring.application.name=farmacia-aed

server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/farmacia_aed}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

